# Generated by Django 2.2.3 on 2020-08-12 15:08

from django.db import migrations, models
import django.db.models.deletion
import user_activity.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=user_activity.models.generate_user_id, max_length=6, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=255)),
                ('tz', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_activity.User')),
            ],
        ),
    ]
