# Generated by Django 2.2.3 on 2020-08-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=None, max_length=6, primary_key=True, serialize=False),
        ),
    ]
