# Generated by Django 2.2.3 on 2020-08-12 07:43

from django.db import migrations, models
import user_activity.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0002_auto_20200812_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=user_activity.models.generate_user_id, max_length=6, primary_key=True, serialize=False),
        ),
    ]
