# Generated by Django 2.2.3 on 2020-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0004_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tz',
            field=models.CharField(max_length=50),
        ),
    ]
